theme: jekyll-theme-time-machine

title: Trabalhos primeiro período da matéria Experiência Criativa PUC-PR.

description: Aqui estão publicados os três trabalhos do primeiro período de Experiência Criativa PUC-PR.
